source 'https://rubygems.org'

ruby '3.2.2'

# Rails core
gem 'rails', '~> 7.1.0'
gem 'puma', '~> 6.0'
gem 'bootsnap', require: false

# Database
gem 'pg', '~> 1.5'

# Monitoring
gem 'prometheus-client'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end 